# Arboles de decisión

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

## Usamos el dataset de vinos https://www.mldata.io/dataset-details/wine/

In [2]:
vinos = pd.read_csv('wine_dataset.csv')
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [4]:
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [5]:
vinos['Wine Type'].value_counts()

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

In [6]:
x = vinos.drop('Wine Type',axis=1)

In [7]:
x.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [8]:
y = vinos['Wine Type']

In [9]:
y.head()

0    One
1    One
2    One
3    One
4    One
Name: Wine Type, dtype: object

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [13]:
x_train.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
9      13.86        1.35  2.27               16.0       98.0           2.98   
47     13.90        1.68  2.12               16.0      101.0           3.10   
13     14.75        1.73  2.39               11.4       91.0           3.10   
147    12.87        4.61  2.48               21.5       86.0           1.70   
118    12.77        3.43  1.98               16.0       80.0           1.63   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
9          3.15                  0.22             1.85             7.22  1.01   
47         3.39                  0.21             2.14             6.10  0.91   
13         3.69                  0.43             2.81             5.40  1.25   
147        0.65                  0.47             0.86             7.65  0.54   
118        1.25                  0.43             0.83             3.40  0.70   

     OD280/OD315 of diluted wines  Proline  
9                            3.55   1045.0  
47                           3.33    985.0  
13                           2.73   1150.0  
147                          1.86    625.0  
118                          2.12    372.0

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
arbol = DecisionTreeClassifier()

In [16]:
arbol.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [17]:
predicciones = arbol.predict(x_test)

In [18]:
predicciones

array(['One', 'Two', 'One', 'Two', 'Two', 'Two', 'Three', 'One', 'Two',
       'Two', 'One', 'Two', 'Two', 'One', 'Three', 'One', 'Three', 'Two',
       'One', 'One', 'Three', 'One', 'Two', 'Two', 'Two', 'Three', 'One',
       'One', 'Three', 'One', 'One', 'Three', 'One', 'Three', 'Two',
       'One', 'One', 'Two', 'One', 'Two', 'Two', 'One', 'One', 'Two',
       'One', 'One', 'Three', 'Two', 'Two', 'Three', 'Two', 'One', 'Two',
       'One'], dtype=object)

In [19]:
y_test

54       One
21       One
26       One
97       Two
98       Two
69       Two
173    Three
5        One
72       Two
115      Two
35       One
64       Two
112      Two
34       One
168    Three
56       One
149    Three
59       Two
30       One
37       One
141    Three
46       One
61       Two
116      Two
90       Two
170    Three
55       One
39       One
135    Three
57       One
25       One
159    Three
20       One
144    Three
102      Two
36       One
62       Two
86       Two
31       One
123      Two
60       Two
32       One
16       One
111      Two
52       One
41       One
156    Three
128      Two
151    Three
175    Three
82       Two
10       One
117      Two
53       One
Name: Wine Type, dtype: object

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(classification_report(y_test,predicciones))

              precision    recall  f1-score   support

         One       0.96      0.96      0.96        23
       Three       1.00      0.91      0.95        11
         Two       0.90      0.95      0.93        20

    accuracy                           0.94        54
   macro avg       0.95      0.94      0.95        54
weighted avg       0.95      0.94      0.94        54



In [22]:
print(confusion_matrix(y_test,predicciones))

[[22  0  1]
 [ 0 10  1]
 [ 1  0 19]]
